### PR TITLE
Adding support for new "taxonkit filter" command

### PR DESCRIPTION
**Pull request by standage**
Pursuant to #3, this branch adds support for the new `taxonkit filter` command.

### CODE REVIEW

**Comment by standage** [comment]
Will need to wait to merge this PR until the bug fix in https://github.com/shenwei356/taxonkit/issues/37 is published in a new release.

**Comment by standage** [comment]
Also, need to update the README!

**Comment by shenwei356** [comment]
I update TaxonKit again, changes needed? :)

- `taxonkit filter`:
    - flag `-E/--equal-to` supports multiple values.
- `taxonkit reformat`:
    - **new placeholder `{t}` for `subspecies/strain`, `{T}` for `strain`**.

**Comment by shenwei356** [comment]
Sorry, updated again.

- v0.7.2
    - `taxonkit filter`:
        - flag `-E/--equal-to` supports multiple values.
        - new flag `-n/--save-predictable-norank`: do not discard some special ranks without order when using -L, where rank of the closest higher node is still lower than rank cutoff.
    - `taxonkit reformat`:
        - **new placeholder `{t}` for `subspecies/strain`, `{T}` for `strain`**. Thanks @wqssf102 for feedback.
        - new flag `-S/--pseudo-strain` for using the node with lowest rank as strain name, only if which rank is lower than "species" and not "subpecies" nor "strain". 
- v0.7.1
    - `taxonkit filter`: 
        - disable unnecessary stdin check when using flag `--list-order` or `--list-ranks`. [#36](https://github.com/shenwei356/taxonkit/issues/36)
        - better handling of black list, empty default value: "no rank" and "clade". And you need use `-N/--discard-noranks` to explicitly filter out "no rank", "clade". [#37](https://github.com/shenwei356/taxonkit/issues/37)
        - update help message. Thanks @standage for improve this command! [#38](https://github.com/shenwei356/taxonkit/issues/38)
      
Binaries

- [taxonkit_linux_arm64.tar.gz](https://github.com/bioforensics/pytaxonkit/files/5867008/taxonkit_linux_arm64.tar.gz)
- [taxonkit_darwin_arm64.tar.gz](https://github.com/bioforensics/pytaxonkit/files/5867005/taxonkit_darwin_arm64.tar.gz)

**Comment by standage** [comment]
Awesome, thanks @shenwei356! I'll open up a separate PR to support the new 0.7.2 features.

**Comment by standage** [comment]
I will test and update when 0.7.2 is published, or when you post AMD binaries.

**Pull request merged**
